# Number of days of inactivity before an issue becomes stale
daysUntilStale: 300
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
    - pinned
    - security
    - correctness
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. You can
    prevent this by labelling it as pinned, security or correctness.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
