name: our-world-in-data
recipe: wordpress
config:
  webroot: web
  via: nginx
  xdebug: true
services:
  appserver:
    run:
      - composer install
  node:
    type: node
    build:
      - cd web/app/plugins/owid-wordpress-admin && yarn && yarn build
    run_as_root:
      - ln -s /user/.ssh/config /var/www/.ssh/config
  database:
    portforward: 3306
    healthcheck:
  database-grapher:
    type: mysql
    portforward: 3307
    healthcheck:
tooling:
  db-refresh:
    description: Dumps production database and imports it
    cmd:
      - appserver: ssh owid-live "sudo mysqldump --default-character-set=utf8mb4 live_wordpress -r ~/live_wordpress.sql"
      - appserver: rsync -havz --progress owid-live:live_wordpress.sql /app
      - database: /helpers/sql-import.sh live_wordpress.sql
