name: our-world-in-data
recipe: wordpress
# Uncomment to start using env variables
# env_file:
#   - .env
config:
  webroot: web
  via: nginx
  xdebug: true
  config:
    vhosts: .lando/vhosts.conf.tpl
services:
  appserver:
    build_as_root:
      - ln -sf /user/.ssh/config /var/www/.ssh/config
  node:
    type: node
  database:
    portforward: 3306
    healthcheck:
  database-grapher:
    type: mysql
    creds:
      user: grapher
      password: grapher
      database: grapher
    portforward: 3307
    healthcheck:
events:
  pre-build:
    # post-start:
    - appserver: composer install
    - node: cd web/app/plugins/owid && yarn
tooling:
  db-refresh:
    description: Dumps production databases (live_wordpress, owid_metadata) and imports them
    cmd:
      - appserver: ssh owid-live "sudo mysqldump --default-character-set=utf8mb4 live_wordpress -r live_wordpress.sql && gzip -f live_wordpress.sql"
      - appserver: rsync -havz --progress owid-live:live_wordpress.sql.gz . && curl -LO https://files.ourworldindata.org/owid_metadata.sql.gz
      - database: /helpers/sql-import.sh live_wordpress.sql.gz
      - database-grapher: /helpers/sql-import.sh owid_metadata.sql.gz
  build:
    description: Installs dependencies and builds app
    service: node
    cmd:
      - cd web/app/plugins/owid && yarn build
  deploy:
    description: Deploys app to target
    cmd:
      - appserver: ./scripts/deploy.sh
