name: our-world-in-data
recipe: wordpress
config:
  webroot: web
  via: nginx
  xdebug: true
services:
  appserver:
    run:
      - composer install
  node:
    type: node
    build:
      - cd web/app/plugins/owid-wordpress-admin && yarn && yarn build
  database:
    portforward: 3306
    healthcheck:
