name: our-world-in-data
recipe: wordpress
# Uncomment to start using env variables
# env_file:
#   - .env
config:
  webroot: web
  via: nginx
  xdebug: true
  config:
    vhosts: .lando/vhosts.conf.tpl
services:
  appserver:
    run:
      - composer install
  node:
    type: node
    build:
      - cd web/app/plugins/owid-wordpress-admin && yarn && yarn build
    build_as_root:
      - ln -sf /user/.ssh/config /var/www/.ssh/config
  database:
    portforward: 3306
    healthcheck:
  database-grapher:
    type: mysql
    creds:
      user: grapher
      password: grapher
      database: grapher
    portforward: 3307
    healthcheck:
tooling:
  db-refresh:
    description: Dumps production databases (live_wordpress, owid_metadata) and imports them
    cmd:
      - appserver: ssh owid-live "sudo mysqldump --default-character-set=utf8mb4 live_wordpress -r live_wordpress.sql && gzip -f live_wordpress.sql"
      - appserver: rsync -havz --progress owid-live:live_wordpress.sql.gz . && curl -LO https://files.ourworldindata.org/owid_metadata.sql.gz
      - database: /helpers/sql-import.sh live_wordpress.sql.gz
      - database-grapher: /helpers/sql-import.sh owid_metadata.sql.gz
