name: our-world-in-data
recipe: wordpress
env_file:
  - .env
config:
  webroot: web
  via: nginx
  xdebug: true
  config:
    vhosts: .lando/vhosts.conf.tpl
services:
  appserver:
    build_as_root:
      - ln -sf /user/.ssh/config /var/www/.ssh/config
  node:
    type: node
  database:
    portforward: 3306
    healthcheck:
  database-grapher:
    type: mysql
    creds:
      user: grapher
      password: grapher
      database: grapher
    portforward: 3307
    healthcheck:
events:
  pre-build:
    # post-start:
    - appserver: composer install
    - node: cd web/app/plugins/owid && yarn
tooling:
  refresh:
    description: Refreshes local content (--help for more information)
    service: appserver
    cmd: .lando/scripts/refresh.sh
  build:
    description: Installs dependencies and builds app
    service: node
    cmd: cd web/app/plugins/owid && yarn build
  deploy:
    description: Deploys app to target
    service: appserver
    cmd: .lando/scripts/deploy.sh
