compressionLevel: mixed

enableGlobalCache: false

logFilters:
    - code: YN0013 # A package cannot be found in the cache for the given package and will be fetched from its remote location.
      level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.0.cjs
