version: "3.7"

services:
    db:
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: weeniest-stretch-contaminate-gnarl

    db-load-data:
        image: mysql:5.7
        command: "bash /app/create-and-fill-grapher-db.sh && bash /app/create-and-fill-wordpress-db.sh"
        volumes:
            - ./devTools/docker:/app
        environment:
            DB_ROOT_PASS: weeniest-stretch-contaminate-gnarl
            DB_HOST: db
        depends_on:
            - db

    web:
        image: nginx:1.21
        ports:
            - 8080:80
        volumes:
            - ./wordpress/.lando/config/vhosts.conf:/etc/nginx/conf.d/default.conf
            - ./wordpress:/app
        depends_on:
            - fpm

    fpm:
        build:
            context: ./devTools/docker/wordpress-php-docker
        ports:
            - 9000:9000
        volumes:
            - ./wordpress/.lando/config/php.ini:/usr/local/etc/php/php.ini
            - ./wordpress:/app
        depends_on:
            - db

    wordpress-install:
        build:
            context: ./devTools/docker/wordpress-php-docker
        command: "composer install --no-interaction"
        volumes:
            - ./wordpress:/app

volumes:
    mysql_data:
