name: Assign priority based on label
on:
    issues:
        types:
            - opened
            - reopened
            - labeled
            - unlabeled

jobs:
    prio:
        name: Sync issue priority to project board
        runs-on: ubuntu-latest
        steps:
            - uses: owid/actions/assign-priority@main
              with:
                  PROJECT_ISSUES_TOKEN: ${{ secrets.PROJECT_ISSUES_TOKEN }}
