name: Auto-deploy to GitHub Pages

# Builds and deploys Storybook and a Jest coverage report to owid.github.io.
# Most stuff in here is handled by https://github.com/marketplace/actions/deploy-to-github-pages

on:
    push:
        branches:
            - master
jobs:
    build-deploy-storybook-coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
              with:
                  persist-credentials: false

            # Use Node version specified in .nvmrc
            # https://github.com/actions/setup-node/issues/32#issuecomment-525791142
            - name: Read .nvmrc
              id: nvm
              run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"

            - name: Use Node.js (.nvmrc)
              uses: actions/setup-node@v2
              with:
                  node-version: "${{ steps.nvm.outputs.NVMRC }}"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn --frozen-lockfile --network-concurrency 1

            # Note: running these two build steps subsequently means that if either `buildStorybook` or `coverage` fails,
            # neither of them is deployed :(
            # Let's hope this doesn't happen too often

            - name: Build JS
              run: yarn buildTsc

            - name: Build Storybook 🔧
              run: yarn buildStorybook

            - name: Generate Jest coverage report 🃏
              run: yarn buildCoverage

            - name: Generate coverage badge 🔖
              run: |
                  mkdir -p badges
                  yarn add lcov-badge@1.0.4
                  yarn lcov-badge -o badges/coverage.svg coverage/lcov.info

            # We're using two subsequent deploys instead of making them parallel because `github-pages-deploy-action`
            # force-pushes, and if we have two deploys running at the same time that might lead to missing update situations.

            - name: Deploy Storybook 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  token: ${{ secrets.STORYBOOK_DEPLOY_ACCESS_TOKEN }}
                  branch: master
                  folder: .storybook/build
                  repository-name: owid/owid.github.io
                  target-folder: stories
                  commit-message: |-
                      🤖 update Storybook
                      owid/owid-grapher@${{ github.sha }}
                  git-config-name: owidbot
                  git-config-email: tech@ourworldindata.org

            - name: Deploy Coverage Report 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  token: ${{ secrets.STORYBOOK_DEPLOY_ACCESS_TOKEN }}
                  branch: master
                  folder: coverage/lcov-report
                  repository-name: owid/owid.github.io
                  target-folder: coverage
                  commit-message: |-
                      🤖 update coverage report
                      owid/owid-grapher@${{ github.sha }}
                  git-config-name: owidbot
                  git-config-email: tech@ourworldindata.org

            - name: Deploy Badges 🚀
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  token: ${{ secrets.STORYBOOK_DEPLOY_ACCESS_TOKEN }}
                  branch: master
                  folder: badges
                  repository-name: owid/owid.github.io
                  target-folder: badges
                  commit-message: |-
                      🤖 update badges
                      owid/owid-grapher@${{ github.sha }}
                  git-config-name: owidbot
                  git-config-email: tech@ourworldindata.org
