name: Continuous Integration
on: [push]

jobs:
    # Checks for prettify errors, TypeScript errors and runs Jest tests.
    testcheck:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - uses: ./.github/actions/setup-node-yarn-deps

            - name: Register Problem Matcher
              run: echo "##[add-matcher].github/problemMatchers/tsc.json"

            - name: Run prettier
              run: yarn testPrettierAll

            - name: Run tsc build
              run: yarn buildTsc

            - name: Run jest
              run: yarn testJest

    # Runs `bundlewatch` on the code to see if our Webpack build assets exceed a given file size.
    bundlewatch:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v2

            - uses: ./.github/actions/setup-node-yarn-deps
            - uses: ./.github/actions/build-tsc

            - name: Run bundlewatch
              run: yarn testBundlewatch
              env:
                  BUNDLEWATCH_GITHUB_TOKEN: "${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}"
