name: Upload to DO Spaces
on:
    push:
        branches:
            - master
        paths:
            - "packages/@ourworldindata/grapher/src/schema/**"
jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@master
            - uses: hustcer/setup-nu@v3
              with:
                  version: "0.80" # Don't use 0.80 here, as it was a float number and will be convert to 0.8, you can use v0.80/0.80.0 or '0.80'
            - run: |
                  (ls packages/@ourworldindata/grapher/src/schema/*.yaml
                  | take 1
                  | each {|yaml|
                      open $yaml.name
                      | to json
                      | save ($yaml.name
                          | path parse
                          | upsert extension "json"
                          | path join) })
              shell: nu {0}
            - run: |
                  ( ls packages/@ourworldindata/grapher/src/schema/*.yaml
                    | each (cp $in.name ($in.name | path parse | upsert stem { |filename| $filename.stem | split row "." | $"($in.0).latest" } | path join ))
                  )
              shell: nu {0}
            - uses: BetaHuhn/do-spaces-action@v2
              with:
                  access_key: ${{ secrets.DO_ACCESS_KEY}}
                  secret_key: ${{ secrets.DO_SECRET_KEY }}
                  space_name: owid-public
                  space_region: nyc3
                  source: packages/@ourworldindata/grapher/src/schema
                  out_dir: schemas
